name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830074810060d55247b3f35ca64793b47f96292e8c2195e451d02a5ae814d337"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21"]
