name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "351d8bdd2731941c86521693be2d17846e6f4867751709365ee3416880a12eec"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21"]
