name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7542f8d087abc02a6593a2f119e71bad9957727655d0da7a95d05cdcb7891f83"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.8"
