name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b8fb3218e5e4cfe3dd58a822620694e744f97ab92594515eff879c636c4012a"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.8"

[options]
acceptable-game-versions = ["1.21.3"]
