name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f82b4898643e302aaff2bcd1087bc74cb4359bb1c7837f023db7e98e1df163db"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.8"
