name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450bd75aa73193e526d8d00be8e20adfb6374d0aeddd99d56c4deff7be51fcc7"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.8"
