name = "Survival"
author = "Scott Gould <greysilly7@gmail.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05b69cbc401f0cf0ce50d65a5bbe019be22dd968f900fe65d96f3d1b156ddd40"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.8"

[options]
acceptable-game-versions = ["1.21.3"]
