name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f38dbb635608ba776de161a69a7208c8f7ea3edf2962256fc6939660ea9530b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
