name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7391cedd750d6f7994a266c03e4e5f6b0078d1324073a422c8865639ab64ee58"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
