name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11f47938310609844944af3f97dc07c5530046a343c0144b2ce7df1ba6e97310"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
