name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f394c528738ffb5321b0c4ebf70a1aad35072c7d3bf80ec3120809a0f42a7a1"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
