name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb475a6397ed0e6ac775d99655d1682e1fc67cf3a100d4ad605ff813a18cd56f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
