name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24ccef091a83610d7db4325239c3e15e81319d4bdb842e5844f6e3df198ccd95"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
