name = "iremia-lobby"
author = "iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "036576f96d59eef3032348ab692232bcfdbd678c79e578cc192e39f38148093d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
