name = "iremia-creative"
author = "Iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b9233a5e8651d0aa7e6fe525e92b164be34b26165a950ba2847b48f9a9f2e32"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.20"]
