name = "iremia-creative"
author = "Iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398fa422c68c63e46c77c2e25816ff3d23ad734d79eb218da5b9f86f5c46dca4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.20"]
