name = "iremia-creative"
author = "Iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7f23019afa249edcadbf54afd5576a91c01089c70546045732bc7586e78d2b4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21"]
