name = "iremia-creative"
author = "Iremia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73f5f4d054e9284f3fda7f96fb3a239008bfa02117bd5216cfcc06380ae77b35"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.20"]
